### ISSUE TITLE
How is this to be used?

### ISSUE THREAD

**Issue by IanAber** [einride/pid-go#87]
Not having any experience with PID controlelrs I need a nudge to get this going.

I have a water heating system that has a pump to push water through a set of solar panels to heat up a large tank. I thought I could employ this controller to manage the pump speed based on the temperature of the hot tank vs the temperature of the water coming off the solar panels. My problem is that I don't really understand how I should be using the controller.

I set the ReferenceSignal  to the difference in temperature I am looking for, e.g 3.0 Celsius. Then I set the actual value to the observed difference in the two measured temperatures. I am sampling every 5 seconds.

Is this correct or am I completely missing the point?

Once I get the result by asking for the State, how should I interpret it? Should I use the ControlSignal to adjust the pump speed? Obviously it would need to be capped at 100% but should that somehow be fed back tot he controller?

Please forgive my ignorance here.

**Comment by erikbohnsack** [comment]
Hello @IanAber! Cool to see that you have found this repository in the hunt for what seems to be some fun home automation! Sorry about the late answer. 

Thanks for a good explanation of your system. I will try to give a code example below! Don't be afraid to shoot off any follow-up questions! 

Just to start with, systems control theory, including PID controllers, get complex very fast. The fun thing with PIDs is that you can quite easily _try_ it out and _try_ to tune it without having being a rocket scientist. To get a really well-tuned PID however (both stable and fast), some in-depth theoretical knowledge is most likely needed. 

With that said, you are definitely on the right track! In code, it would look something like this when abstracting away the pump and thermometers: 
```
type Pump interface {
	Control(value float64)
}

type Thermometer interface {
	MeasureTemperatureCelsius() float64
}

func runPumpController(
	ctx context.Context,
	pump Pump,
	tankThermometer Thermometer,
	panelThermometer Thermometer,
) {
	const referenceDifference = 3.0
	controller := pid.Controller{
		Config: pid.ControllerConfig{
			ProportionalGain: 2.0, 
			IntegralGain:     1.0,
			DerivativeGain:   0, // think we should be mighty fine without a derivative part
		},
	}
	const samplingInterval = 5 * time.Second
	ticker := time.NewTicker(samplingInterval)
	for {
		select {
		case <-ctx.Done(): // to return when the above given context is Done
                        return
		case <-ticker.C:
			tankTemp := tankThermometer.MeasureTemperatureCelsius()
			panelsTemp := panelThermometer.MeasureTemperatureCelsius()
			actualDifference := tankTemp - panelsTemp
			controller.Update(pid.ControllerInput{
				ReferenceSignal:  referenceDifference,
				ActualSignal:     actualDifference,
				SamplingInterval: 5 * time.Second,
			})
			pump.Control(controller.State.ControlSignal)
		}
	}
}
```

This does not take into account the limitation of the pump input (as you say 100%), however I think with the `integral` part of the controller, it might just work well without it. If you want that, you could look at the `TrackingController`, which except for adding low-pass filter for the derivative term and `AntiWindUp` to not let the integral part sky-rocket, it adds `MaxOutput` and `MinOutput`, to take into account the limitation of the controller when calculating the ControlSignal.  

A final recommendation; even if you don't want to go full systems-engineering-theoretical to guarantee a stable controller, I still think it could be worthwhile to try to model your system. By modelling your system you will be able to simulate the controller and get a feel of how the PID acts. Maybe you even have some real data to play around with here even? 

Hope this helped! Let me know if there are any other questions!

Best, 
Erik

**Comment by IanAber** [comment]
This is really great information. I am truly grateful for the time you have taken. I will try it all out as soon as I get a chance.
Ian Abercrombie


￼

***@***.*** ***@***.***>
Phone: +1 (352) 281-6286
www.CedarTechnology.com <http://www.cedartechnology.com/>

**Comment by erikbohnsack** [comment]
Glad to hear @IanAber! :)
